### ISSUE TITLE
After clicking on map, the users <back> button takes them two pages back.

### ISSUE THREAD

**Issue by jimurl** [AmericanAvalanche/avalanche.org-API-Client#2]
STR:
1- go to a distinctive page on your website, let's say your 'about us' page.
2- navigate to the home page, or page where the avalanche.org API map lies.
3-click on the map on an advisory region.
4- click the back button, once.

Expected behavior would be that the user ends up on the home page ( or page with the map ). Instead, we end up on the About Us page. Tested on GNFAC and BTAC.

**Comment by andyanderso** [comment]
I can confirm that on the SAC site as well.

**Comment by ccorey** [comment]
Thanks - this is now fixed. Opening a new link in the main window was different depending on if you were using an iframe or not, and the code was originally written for the iframe use case. It now detects whether you're using an iframe or not, and opens the link accordingly.

No updates to the API client are needed...it was all in the API itself, so it should just work.
