### ISSUE TITLE
Info hover box is covered by map controls

### ISSUE THREAD

**Issue by andyanderso** [AmericanAvalanche/avalanche.org-API-Client#3]
The danger rating/info hover box hides behind the map controls if they overlap. Is there a way to set a higher z-index on the popup window?

**Comment by andyanderso** [comment]
Adding `#avy-zoneinfo {z-index:10;}` to the client website css works great to fix this.

**Comment by ccorey** [comment]
I've added your z-index to the style sheet provided by the API. When this is live I will close the issue.
